name: CI

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    name: Test
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3

      - uses: supabase/setup-cli@v1
        with:
          version: 0.34.1

      - run: supabase init
      - run: supabase start

      - name: Verify migration scripts are executable
        run: supabase db reset

      # - name: Run pgTAP tests
      #   run: supabase db test

      - run: supabase gen types typescript --local > types.ts
      - name: Verify generated types are checked in
        run: |
          if [ "$(git diff --ignore-space-at-eol types.ts | wc -l)" -gt "0" ]; then
            echo "Detected uncommitted changes after build. See status below:"
            git diff
            exit 1
          fi
