name: Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  staging:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: supabase/setup-cli@v1
        with:
          version: 0.34.1

      - run: supabase init
      - run: supabase db remote set ${{ secrets.DB_URL }}
      - run: supabase db push
